# Generated by Django 5.0.2 on 2024-11-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='country name')),
                ('code', models.CharField(max_length=10, verbose_name='country code')),
                ('phone_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='country phone code')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='country region')),
                ('sub_region', models.CharField(blank=True, max_length=100, null=True, verbose_name='country sub region')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'db_table': 'CountryMaster',
            },
        ),
    ]
