# Generated by Django 5.0.2 on 2024-11-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='currency code')),
                ('display_name', models.CharField(max_length=100, verbose_name='currency display name')),
                ('base_currency', models.BooleanField(default=True, verbose_name='base currency')),
                ('symbol', models.CharField(default='', max_length=50, verbose_name='currency symbol')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='currency description')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'db_table': 'Currency',
            },
        ),
    ]
