# Generated by Django 5.0.2 on 2024-11-04 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(max_length=100, unique=True, verbose_name='Emp Code')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('date_of_joining', models.DateField(verbose_name='Date of Joining')),
                ('division', models.CharField(blank=True, max_length=100, null=True, verbose_name='Division')),
                ('designation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Designation')),
                ('mobile', models.CharField(blank=True, max_length=10, null=True, verbose_name='Mobile')),
                ('emergency_contact', models.CharField(blank=True, max_length=10, null=True, verbose_name='Emergency Contact')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('current_address', models.TextField(verbose_name='Current Address')),
                ('permanent_address', models.TextField(verbose_name='Permanent Address')),
                ('total_experience', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Total Experience')),
                ('experience_with_new_company', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Experience with Us')),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried'), ('I Rather Do Not Say', 'I Rather Do Not Say')], default='Married', max_length=50, verbose_name='Marital Status')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('I Rather Do Not Say', 'I Rather Do Not Say')], default='Male', max_length=100, verbose_name='Gender')),
                ('aadhar_card_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Aadhar Card Number')),
                ('pan_card', models.CharField(blank=True, max_length=10, null=True, verbose_name='PAN')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name')),
                ('bank_account_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Account Number')),
                ('bank_ifsc', models.CharField(blank=True, max_length=11, null=True, verbose_name='Bank IFSC')),
                ('passport_image', models.ImageField(blank=True, null=True, upload_to='employee/passport_image/', verbose_name='Image')),
                ('is_leader', models.BooleanField(blank=True, null=True, verbose_name='Is Leader')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['emp_code'],
            },
        ),
    ]
